### ISSUE TITLE
Poisson to zinfl poisson comparison?

### ISSUE THREAD

**Issue by nputnam1415** [brentonk/games#1]
I'm a Teaching Assistant tasked with writing example code for students to use about the Vuong and Clarke tests. I'm running into two issues:
-the zero-inflated models I can find in R are all of a special class, 'zeroinfl', which is not included in your selection structure. I fixed this by hard-inserting 'glm' into their class with 
class(zipois_adj) = list("zeroinfl", "glm")
but if you have any advice on a smoother solution, I would appreciate it. 

The more pressing issue is in the indivLogLiks function. It seems incapable of handling any non-games models other than binomial glms and non-glm linear models. I always progress through the if-else chain until 
else {
stop("model is not of a supported class").

Is there any way to use vuong() to compare Poisson models? I know you haven't worked on this project in a while, but I would deeply appreciate any advice you can give me on how to make this work.

**Comment by brentonk** [comment]
I'm not familiar enough with the zero-inflated model functions out there to say exactly. What you'll need is a vector of individual log-likelihoods, where each entry in the vector corresponds to an observation used to fit the model. You'll probably want to dig into the code of the model function you're using to obtain estimates, find the log-likelihood function is maximizing, and use that (possibly modifying it so as not to take a sum) to obtain the observationwise log-likelihoods. Alternatively, and perhaps more easily, you can just write a function to calculate the individual log-likelihoods from the fitted model results.

I'm closing this issue since interoperability with zero-inflated models isn't in the scope of the games package — there's no sensible use case for performing a model comparison between a count model and the models included here. If you have further questions about the games package code, feel free to email me.
